"""empty message

Revision ID: eb154dad0fb4
Revises: e22cb41423ca
Create Date: 2025-02-07 13:28:36.645536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb154dad0fb4'
down_revision = 'e22cb41423ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sign_up')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sign_up',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sign_up_pkey'),
    sa.UniqueConstraint('email', name='sign_up_email_key'),
    sa.UniqueConstraint('phone', name='sign_up_phone_key')
    )
    # ### end Alembic commands ###
