"""Agregando el campo body a Posts

Revision ID: efe99aba57b6
Revises: 4ae91ebba058
Create Date: 2025-02-03 12:39:25.169429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe99aba57b6'
down_revision = '4ae91ebba058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('body')

    # ### end Alembic commands ###
